# Generated by Django 5.2.4 on 2025-11-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='workflow.category')),
            ],
        ),
        migrations.CreateModel(
            name='Workflows',
            fields=[
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('workflow_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('end_logic', models.CharField(blank=True, choices=[('', 'None'), ('asset', 'Asset Management'), ('budget', 'Budget Management'), ('notification', 'Send Notification')], help_text='Optional end‐condition to trigger when workflow completes.', max_length=32)),
                ('category', models.CharField(max_length=64)),
                ('sub_category', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deployed', 'Deployed'), ('paused', 'Paused'), ('initialized', 'Initialized')], default='draft', max_length=16)),
                ('low_sla', models.DurationField(blank=True, help_text='SLA for low priority', null=True)),
                ('medium_sla', models.DurationField(blank=True, help_text='SLA for medium priority', null=True)),
                ('high_sla', models.DurationField(blank=True, help_text='SLA for high priority', null=True)),
                ('urgent_sla', models.DurationField(blank=True, help_text='SLA for urgent priority', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'category', 'sub_category'), name='unique_category_subcategory_per_user')],
            },
        ),
    ]
