# Generated by Django 5.2.1 on 2025-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflows',
            name='end_logic',
            field=models.CharField(blank=True, choices=[('', 'None'), ('asset', 'Asset Management'), ('budget', 'Budget Management'), ('notification', 'Send Notification')], default='asset', help_text='Optional end-condition to trigger when workflow completes.', max_length=32),
        ),
    ]
