# Generated by Django 5.2.1 on 2025-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_workflows_end_logic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflows',
            name='unique_main_sub_per_workflow',
        ),
        migrations.RenameField(
            model_name='workflows',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workflows',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='workflows',
            name='category',
            field=models.CharField(help_text='Top‐level category name (previously a FK).', max_length=64),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='end_logic',
            field=models.CharField(blank=True, choices=[('', 'None'), ('asset', 'Asset Management'), ('budget', 'Budget Management'), ('notification', 'Send Notification')], help_text='Optional end‐condition to trigger when workflow completes.', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='sub_category',
            field=models.CharField(help_text='Sub‐category name (previously a FK).', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='workflows',
            constraint=models.UniqueConstraint(fields=('user_id', 'category', 'sub_category'), name='unique_category_subcategory_per_user'),
        ),
    ]
