# Generated by Django 5.2.1 on 2025-06-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_remove_workflows_unique_main_sub_per_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflows',
            name='high_sla',
            field=models.DurationField(blank=True, help_text='SLA for high priority', null=True),
        ),
        migrations.AddField(
            model_name='workflows',
            name='low_sla',
            field=models.DurationField(blank=True, help_text='SLA for low priority', null=True),
        ),
        migrations.AddField(
            model_name='workflows',
            name='medium_sla',
            field=models.DurationField(blank=True, help_text='SLA for medium priority', null=True),
        ),
        migrations.AddField(
            model_name='workflows',
            name='urgent_sla',
            field=models.DurationField(blank=True, help_text='SLA for urgent priority', null=True),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='sub_category',
            field=models.CharField(max_length=64),
        ),
    ]
