# Generated by Django 5.2.1 on 2025-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0005_workflows_high_sla_workflows_low_sla_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflows",
            name="department",
            field=models.CharField(default="marco", max_length=64),
            preserve_default=False,
        ),
    ]
