# Generated by Django 5.2.4 on 2025-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRobin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('current_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tickets_roundrobin',
            },
        ),
        migrations.CreateModel(
            name='TicketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_data', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['ticket_number'], name='tickets_tic_ticket__1684e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_data', models.JSONField()),
                ('is_task_allocated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_ticket_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('source_service', models.CharField(db_index=True, default='ticket_service', max_length=50)),
                ('status', models.CharField(blank=True, db_index=True, default='New', max_length=20, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticket_number'], name='tickets_wor_ticket__059118_idx'), models.Index(fields=['original_ticket_id'], name='tickets_wor_origina_801822_idx'), models.Index(fields=['status'], name='tickets_wor_status_6eae60_idx')],
            },
        ),
    ]
