# Generated by Django 5.2.1 on 2025-06-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowticket",
            name="opened_on",
        ),
        migrations.RemoveField(
            model_name="workflowticket",
            name="position",
        ),
        migrations.RemoveField(
            model_name="workflowticket",
            name="sla",
        ),
        migrations.RemoveField(
            model_name="workflowticket",
            name="ticket_id",
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="resolution_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="response_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="submit_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="ticket_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="time_closed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowticket",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="customer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="department",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="original_ticket_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Urgent", "Urgent"),
                ],
                db_index=True,
                default="Low",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="source_service",
            field=models.CharField(
                db_index=True, default="ticket_service", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                    ("On Hold", "On Hold"),
                ],
                db_index=True,
                default="New",
                max_length=20,
            ),
        ),
    ]
