# Generated by Django 5.2.1 on 2025-06-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_remove_workflowticket_opened_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowticket",
            name="opened_on",
            field=models.TextField(blank=True, null=True),
        ),
    ]
