# Generated by Django 5.2.1 on 2025-06-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_workflowticket_opened_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowticket",
            name="opened_on",
        ),
    ]
