# Generated by Django 5.2.1 on 2025-06-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_remove_workflowticket_opened_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflowticket",
            old_name="ticket_number",
            new_name="ticket_id",
        ),
    ]
