# Generated by Django 5.2.1 on 2025-06-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_rename_ticket_number_workflowticket_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowticket",
            name="original_ticket_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Urgent", "Urgent"),
                ],
                db_index=True,
                default="Low",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflowticket",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "New"),
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                    ("On Hold", "On Hold"),
                ],
                db_index=True,
                default="New",
                max_length=20,
                null=True,
            ),
        ),
    ]
