# Generated by Django 5.2.1 on 2025-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_alter_workflowticket_original_ticket_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowticket",
            name="department",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
