# Generated by Django 5.2.1 on 2025-06-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_workflowticket_department'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflowticket',
            name='tickets_wor_custome_49d788_idx',
        ),
        migrations.RenameField(
            model_name='workflowticket',
            old_name='customer',
            new_name='employee',
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['employee'], name='tickets_wor_employe_4327d8_idx'),
        ),
    ]
