# Generated by Django 5.2.1 on 2025-06-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_workflowticket_tickets_wor_custome_49d788_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, default='Low', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workflowticket',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Open', 'Open'), ('On Process', 'On Process'), ('On Hold', 'On Hold'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], db_index=True, default='New', max_length=20, null=True),
        ),
    ]
