# Generated by Django 5.2.3 on 2025-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100, unique=True)),
                ('asset_id', models.IntegerField()),
                ('asset_name', models.CharField(max_length=255)),
                ('requestor', models.CharField(max_length=100)),
                ('requestor_location', models.CharField(max_length=255)),
                ('checkout_date', models.DateField()),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_checkout', models.BooleanField(default=True)),
                ('checkout_ref_id', models.CharField(default='1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Checkout',
                'verbose_name_plural': 'Asset Checkouts',
                'ordering': ['-checkout_date'],
            },
        ),
    ]
