# Generated by Django 5.2.3 on 2025-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscheckout', '0002_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='asset_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
