# Generated by Django 5.2.3 on 2025-06-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscheckout', '0003_alter_checkout_asset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_checkout',
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
