# Generated by Django 5.2.3 on 2025-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscheckout', '0004_remove_checkout_is_checkout_checkout_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='condition',
            field=models.IntegerField(default=1),
        ),
    ]
