# Generated by Django 5.2.3 on 2025-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscheckout', '0005_checkout_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_ref_id',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
    ]
