# Generated by Django 5.2.3 on 2025-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscheckout', '0006_alter_checkout_checkout_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='condition',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
