# Generated by Django 5.2.1 on 2025-06-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amscheckout", "0007_alter_checkout_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="requestor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
