# Generated by Django 5.2.1 on 2025-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscheckout', '0008_checkout_requestor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='description',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='subject',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
