# Generated by Django 5.2.1 on 2025-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification (e.g., transferred_by, old_assignee)'),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('task_assignment', 'Task Assignment'), ('task_transfer_out', 'Task Transferred From You'), ('task_transfer_in', 'Task Transferred To You'), ('task_escalation', 'Task Escalation'), ('task_completed', 'Task Completed'), ('task_status_update', 'Task Status Update'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_reopened', 'Ticket Reopened'), ('sla_warning', 'SLA Warning'), ('sla_breach', 'SLA Breach'), ('workflow_step_change', 'Workflow Step Change'), ('comment_added', 'Comment Added'), ('mention', 'Mentioned in Comment'), ('system', 'System Notification')], default='system', help_text='Type of notification for filtering and display', max_length=50),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='related_task_id',
            field=models.CharField(blank=True, help_text='Related task ID for navigation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='related_ticket_number',
            field=models.CharField(blank=True, help_text='Related ticket number for navigation', max_length=100, null=True),
        ),
    ]
