# Generated by Django 5.2.9 on 2025-12-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_related_task_id_to_task_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailCache',
            fields=[
                ('user_id', models.IntegerField(help_text='User ID from auth service', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Whether user is active')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last sync timestamp')),
            ],
            options={
                'verbose_name': 'User Email Cache',
                'verbose_name_plural': 'User Email Cache',
                'db_table': 'user_email_cache',
            },
        ),
    ]
