# Generated by Django 5.2.9 on 2025-12-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_user_email_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inappnotification',
            name='related_task_item_id',
        ),
    ]
