# Generated by Django 5.2.4 on 2025-11-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='ID of user who performed action', null=True)),
                ('username', models.CharField(blank=True, help_text='Username for audit trail', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email of user who performed action', max_length=254, null=True)),
                ('action', models.CharField(choices=[('create_workflow', 'Created Workflow'), ('update_workflow', 'Updated Workflow'), ('delete_workflow', 'Deleted Workflow'), ('publish_workflow', 'Published Workflow'), ('deploy_workflow', 'Deployed Workflow'), ('pause_workflow', 'Paused Workflow'), ('resume_workflow', 'Resumed Workflow'), ('create_step', 'Created Step'), ('update_step', 'Updated Step'), ('delete_step', 'Deleted Step'), ('reorder_steps', 'Reordered Steps'), ('create_task', 'Created Task'), ('update_task', 'Updated Task'), ('delete_task', 'Deleted Task'), ('assign_task', 'Assigned Task'), ('create_version', 'Created Version'), ('update_version', 'Updated Version'), ('publish_version', 'Published Version'), ('update_sla', 'Updated SLA'), ('update_category', 'Updated Category'), ('other', 'Other Action')], help_text='Type of action performed', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, help_text="Model name (e.g., 'Workflow', 'Step')", max_length=100, null=True)),
                ('target_id', models.IntegerField(blank=True, help_text='ID of object being audited', null=True)),
                ('changes', models.JSONField(blank=True, help_text='Structured JSON describing what changed (old vs new values)', null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the change', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the object being audited', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='audit_audit_user_id_5d0160_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__59bbff_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_c194db_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_c1f818_idx')],
            },
        ),
    ]
