# Generated by Django 5.2.4 on 2025-11-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('step', '0001_initial'),
        ('task', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRoundRobinPointer',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='role.roles')),
                ('pointer', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_instance_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('user_id', models.IntegerField(null=True)),
                ('has_acted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_transition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.steptransition')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
