# Generated by Django 5.2.4 on 2025-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_instance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='stepinstance',
            name='step_instance_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
