# Generated by Django 5.2.1 on 2025-06-22 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
