# Generated by Django 5.2.4 on 2025-11-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflowticket',
            name='tickets_wor_status_6eae60_idx',
        ),
        migrations.AlterField(
            model_name='workflowticket',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
