# Generated by Django 5.2.3 on 2025-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FINANCE_HEAD', 'Finance Head'), ('GENERAL_USER', 'General User')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='log_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('PASSWORD_RESET_CONFIRM', 'Password Reset Confirm'), ('PASSWORD_CHANGE', 'Password Change'), ('TOKEN_REFRESH', 'Token Refresh'), ('PROFILE_VIEW', 'Profile View'), ('PROFILE_UPDATE', 'Profile Update'), ('USER_MANAGEMENT', 'User Management'), ('REGISTER', 'User Registration'), ('ERROR', 'Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ATTEMPTED', 'Attempted')], max_length=20),
        ),
    ]
