# Generated by Django 5.2.1 on 2025-12-31 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentPDFCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpdesk_attachment_id', models.IntegerField(db_index=True, help_text='ID of the TicketAttachment in helpdesk service', unique=True)),
                ('ticket_number', models.CharField(db_index=True, max_length=64)),
                ('original_file_name', models.CharField(max_length=255)),
                ('original_file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('original_file_size', models.IntegerField(help_text='Size in bytes')),
                ('original_content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of original file for invalidation detection', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_supported', 'File type not supported'), ('passthrough', 'Original is already PDF')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('pdf_file', models.FileField(blank=True, help_text='Cached PDF conversion of the original file', null=True, upload_to='pdf_cache/')),
                ('pdf_file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_started_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Attachment PDF Cache',
                'verbose_name_plural': 'Attachment PDF Caches',
                'indexes': [models.Index(fields=['helpdesk_attachment_id'], name='attachments_helpdes_ebd8dd_idx'), models.Index(fields=['ticket_number'], name='attachments_ticket__69ade5_idx'), models.Index(fields=['status'], name='attachments_status_26cfd5_idx'), models.Index(fields=['original_content_hash'], name='attachments_origina_43c25e_idx'), models.Index(fields=['last_accessed_at'], name='attachments_last_ac_01114d_idx')],
            },
        ),
    ]
