# Generated by Django 5.2.3 on 2025-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_firstname_comment_lastname_comment_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='rating',
            field=models.BooleanField(help_text='True (1) for thumbs up, False (0) for thumbs down'),
        ),
    ]
