#bms/budget_service/capstone/settings.py
"""
Django settings for capstone project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
import sys
import dj_database_url


# Auth Service Configuration
AUTH_SERVICE_URL = os.getenv('AUTH_SERVICE_URL', 'http://localhost:8001')



# Detect if running tests
TESTING = 'test' in sys.argv

# Load .env from capstone folder
BASE_DIR = Path(__file__).resolve().parent  # Points to /capstone
load_dotenv(BASE_DIR / '.env')  # Explicit path

# Frontend URL (for password reset links)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'  # Disable in production

# ALLOWED_HOSTS Configuration - Updated for Render with Railway fallback
ALLOWED_HOSTS = []

if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])
else:
    # Render configuration (primary)
    RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    
    # Add Render service domains
    ALLOWED_HOSTS.extend([
        'budget-pro.onrender.com',  # Your budget service domain
        '.onrender.com',  # All Render subdomains
        'api.bms.mapactive.tech',  # Your custom domain
        '.mapactive.tech',  # All subdomains of your custom domain
    ])
    
    # Railway fallback configuration (keep for potential return)
    RAILWAY_APP_HOSTNAME = os.getenv('RAILWAY_PUBLIC_DOMAIN')
    if RAILWAY_APP_HOSTNAME:
        ALLOWED_HOSTS.append(RAILWAY_APP_HOSTNAME)
    
    # Railway domains as fallback
    ALLOWED_HOSTS.extend(['.railway.app', '.up.railway.app'])

# CRITICAL FIX: Always include localhost for internal health checks
# Render performs internal health checks from 127.0.0.1
ALLOWED_HOSTS.extend(['localhost', '127.0.0.1', '0.0.0.0'])

# Remove duplicates and None values
ALLOWED_HOSTS = list(set(filter(None, ALLOWED_HOSTS)))

if not ALLOWED_HOSTS and not DEBUG:
    print("WARNING: ALLOWED_HOSTS is empty in a non-DEBUG environment.")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  
    'django.contrib.staticfiles',
    'cloudinary', 

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'debug_toolbar',
    'django_extensions',

    # Local apps
    # 'users',
    # 'finance',
    # 'budgeting',
    # 'expenses',
    'core',
]

AUTH_USER_MODEL = 'core.User'

AUTHENTICATION_BACKENDS = [
    #'core.authentication.EmailOrPhoneNumberBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============================================================================
# CORS CONFIGURATION - FIXED FOR SHARED DOMAIN AUTHENTICATION
# ============================================================================

# CORS Configuration - Allow frontend to access backend with cookies
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Local frontend
    "https://bms.mapactive.tech",  # BMS Frontend (PRODUCTION)
    "https://login.ticketing.mapactive.tech",  # Centralized Auth Login
    "https://api.ticketing.mapactive.tech",  # Centralized Auth API
    "https://frontend-r2az.onrender.com",  # Old Render frontend (keep for safety or remove)
    "https://budget-pro-static-site.onrender.com",  # Render frontend
    "https://auth-service-cdln.onrender.com",  # Auth service
]

# Add environment variable origins if they exist
if os.getenv('FRONTEND_URL'):
    CORS_ALLOWED_ORIGINS.append(os.getenv('FRONTEND_URL'))
if os.getenv('AUTH_SERVICE_URL'):
    CORS_ALLOWED_ORIGINS.append(os.getenv('AUTH_SERVICE_URL'))

# Added Railway URLs as fallback
railway_frontend = os.getenv('RAILWAY_FRONTEND_URL')
if railway_frontend:
    CORS_ALLOWED_ORIGINS.append(railway_frontend)

# Filter out None values
CORS_ALLOWED_ORIGINS = [origin for origin in CORS_ALLOWED_ORIGINS if origin]

# CRITICAL: Allow credentials (cookies) to be sent cross-origin
# This enables the browser to send HttpOnly cookies from .mapactive.tech
CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOW_ALL_ORIGINS should be False in production for security
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================================================
# CSRF CONFIGURATION
# ============================================================================

# CSRF Configuration - Required for Django 4.0+ cross-origin POST requests
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'https://bms.mapactive.tech',
    'https://login.ticketing.mapactive.tech',
]

# Add from environment variable if exists
env_csrf_origins = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if env_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in env_csrf_origins.split(',') if origin.strip()])

# Clean up list (remove duplicates)
CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS))

# ============================================================================
# COOKIE DOMAIN CONFIGURATION - CRITICAL FOR CROSS-SUBDOMAIN AUTH
# ============================================================================

# Set cookie domain to .mapactive.tech to share across subdomains
COOKIE_DOMAIN = os.getenv('COOKIE_DOMAIN', '.mapactive.tech')

if not DEBUG:
    # Production settings for shared domain cookies
    SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
    CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
    
    # CRITICAL: Use 'None' for SameSite when using cross-origin with credentials
    # This allows cookies to be sent from bms.mapactive.tech to api.bms.mapactive.tech
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
    
    # Secure must be True when SameSite=None (HTTPS required)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    # Development settings
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ============================================================================
# SERVICE-TO-SERVICE API KEYS
# ============================================================================

# Settings for when THIS BMS service calls OTHER services
BMS_AUTH_KEY_FOR_DTS = os.getenv('API_KEY_FOR_BMS_TO_CALL_DTS') # Key BMS uses
API_KEY_FOR_BMS_TO_CALL_AMS = os.getenv('API_KEY_FOR_BMS_TO_CALL_AMS')
API_KEY_FOR_BMS_TO_CALL_HDTS = os.getenv('API_KEY_FOR_BMS_TO_CALL_HDTS')

# --- OUTBOUND WEBHOOKS (BMS -> Other Services) ---
# Where to send updates for Budget Proposals
DTS_STATUS_UPDATE_URL = os.getenv('DTS_STATUS_UPDATE_ENDPOINT_URL') 

# NEW: Where to send updates for Asset Expenses (AMS)
AMS_STATUS_UPDATE_URL = os.getenv('AMS_STATUS_UPDATE_ENDPOINT_URL')

# NEW: Where to send updates for HelpDesk Expenses (HDTS)
HDTS_STATUS_UPDATE_URL = os.getenv('HDTS_STATUS_UPDATE_ENDPOINT_URL')

# Keys expected from client services calling THIS (BMS) service
DTS_CLIENT_API_KEY_EXPECTED = os.getenv('DTS_CLIENT_API_KEY')
TTS_CLIENT_API_KEY_EXPECTED = os.getenv('TTS_CLIENT_API_KEY')
HDS_CLIENT_API_KEY_EXPECTED = os.getenv('HDS_CLIENT_API_KEY')
AMS_CLIENT_API_KEY_EXPECTED = os.getenv('AMS_CLIENT_API_KEY')

SERVICE_API_KEYS = {} # Maps the key value to the client service's name
if DTS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[DTS_CLIENT_API_KEY_EXPECTED] = "DTS"
if TTS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[TTS_CLIENT_API_KEY_EXPECTED] = "TTS"
if HDS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[HDS_CLIENT_API_KEY_EXPECTED] = "HDS"
if AMS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[AMS_CLIENT_API_KEY_EXPECTED] = "AMS"

# Filter out None values if a key isn't set in .env
SERVICE_API_KEYS = {k: v for k, v in SERVICE_API_KEYS.items() if k}

# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ============================================================================
# CLOUDINARY CONFIGURATION (ROBUST)
# ============================================================================

import cloudinary
import cloudinary.uploader
import cloudinary.api
from urllib.parse import urlparse

# Get Cloudinary URL from environment
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL')

if CLOUDINARY_URL:
    # Parse the Cloudinary URL to extract components
    # Format: cloudinary://API_KEY:API_SECRET@CLOUD_NAME
    parsed = urlparse(CLOUDINARY_URL)
    
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': parsed.hostname,  # du7iy1ahe
        'API_KEY': parsed.username,      # 278315874871179
        'API_SECRET': parsed.password,   # bvaJmQMElGxH0SY2ZaiMdQZeXMc
    }
    
    # Configure cloudinary library (for direct uploads via API)
    cloudinary.config(
        cloud_name=parsed.hostname,
        api_key=parsed.username,
        api_secret=parsed.password,
        secure=True  # Always use HTTPS
    )
else:
    # Fallback for local development (if CLOUDINARY_URL not set)
    CLOUDINARY_STORAGE = None

# Media File Storage Configuration
MEDIA_URL = '/media/'

if DEBUG or not CLOUDINARY_URL:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
# ============================================================================
# DEBUG TOOLBAR
# ============================================================================

INTERNAL_IPS = [
    '127.0.0.1',
]

# ============================================================================
# JWT AUTHENTICATION CONFIGURATION - CRITICAL FOR CENTRALIZED AUTH
# ============================================================================

# JWT Signing Key - MUST match the centralized auth service's signing key
# This allows BMS to verify tokens issued by the centralized auth service
# CRITICAL: This MUST be the EXACT same value as in your auth service
JWT_SIGNING_KEY = os.getenv('DJANGO_JWT_SIGNING_KEY', SECRET_KEY)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Match auth service
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Match auth service
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'VERIFYING_KEY': None,
    'SIGNING_KEY': JWT_SIGNING_KEY,  # Use shared signing key
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ============================================================================
# MIDDLEWARE
# ============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'core.middleware.HealthCheckCSRFExemptMiddleware', 
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

CSRF_EXEMPT_URLS = ['/health/']

# ============================================================================
# REST FRAMEWORK CONFIGURATION - CRITICAL FOR AUTHENTICATION
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [ 
        'core.authentication.JWTCookieAuthentication',  # Primary: JWT via cookies or Bearer header (centralized auth)
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback: Standard JWT header auth
        'core.service_authentication.APIKeyAuthentication',  # For service-to-service API keys
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}

# ============================================================================
# CACHE CONFIGURATION
# ============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

ROOT_URLCONF = 'capstone.urls'

# ============================================================================
# DRF SPECTACULAR (API DOCUMENTATION)
# ============================================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Budget Service API",
    "DESCRIPTION": "API for Budget Management",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_SECURITY_SCHEMES": {
        "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'defaultModelsExpandDepth': -1,  # Hide schemas section completely
    },
    'ENUM_NAME_OVERRIDES': {
       'Status0feEnum': 'BudgetProposalStatusEnum',
        'Status1a2Enum': 'ExpenseStatusEnum',
    },
    'TAGS': [  # Organize endpoints by category
        {'name': 'Authentication', 'description': 'User login/logout operations'},
    ],
    'APPEND_COMMON_PREFIX': False,
    'TAGS_SORTER': 'alpha',
    'OPERATION_SORTER': 'method',
}

# ============================================================================
# TEMPLATES
# ============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone.wsgi.application'

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================

DATABASE_URL = os.getenv('DATABASE_URL')

# Allow SQLite for local development when no database config is provided
USE_SQLITE = os.getenv('USE_SQLITE', 'False').lower() == 'true'

if USE_SQLITE or (DEBUG and not DATABASE_URL and not os.getenv('DB_NAME')):
    # SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif DATABASE_URL:
    # Use Railway's DATABASE_URL (recommended)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Fallback to individual environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME') or os.getenv('PGDATABASE'),
            'USER': os.getenv('DB_USER') or os.getenv('PGUSER'),
            'PASSWORD': os.getenv('DB_PASSWORD') or os.getenv('PGPASSWORD'),
            'HOST': os.getenv('DB_HOST') or os.getenv('PGHOST', 'localhost'),
            'PORT': os.getenv('DB_PORT') or os.getenv('PGPORT', '5432'),
        }
    }

# ============================================================================
# SUPERUSER CONFIGURATION
# ============================================================================

DJANGO_SUPERUSER_USERNAME = os.getenv('DJANGO_SUPERUSER_USERNAME')
DJANGO_SUPERUSER_EMAIL = os.getenv('DJANGO_SUPERUSER_EMAIL')
DJANGO_SUPERUSER_PASSWORD = os.getenv('DJANGO_SUPERUSER_PASSWORD')

# ============================================================================
# PASSWORD VALIDATION
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'core.password_validators.CustomPasswordValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum 8 characters as per requirements
            'max_length': 64,  # Maximum 64 characters as per requirements
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {"NAME": "pwned_passwords_django.validators.PwnedPasswordsValidator",
     },  # Check against breached passwords

]

PASSWORD_HASHERS = [
    # 'core.hashers.CustomArgon2PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',      # Strongest
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',      # Default ; Fallback
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# ============================================================================
# INTERNATIONALIZATION
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================================================
# STATIC FILES
# ============================================================================

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
STATIC_URL = 'static/'

# ============================================================================
# DEFAULT AUTO FIELD
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'