"""
Django settings for capstone project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
import sys
import dj_database_url


# Auth Service Configuration
AUTH_SERVICE_URL = os.getenv('AUTH_SERVICE_URL', 'http://localhost:8001')



# Detect if running tests
TESTING = 'test' in sys.argv

# Load .env from capstone folder
BASE_DIR = Path(__file__).resolve().parent  # Points to /capstone
load_dotenv(BASE_DIR / '.env')  # Explicit path

# Frontend URL (for password reset links)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'  # Disable in production

# ALLOWED_HOSTS Configuration - Updated for Render with Railway fallback
ALLOWED_HOSTS = []

if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])
else:
    # Render configuration (primary)
    RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    
    # Add Render service domains
    ALLOWED_HOSTS.extend([
        'budget-pro.onrender.com',  # Your budget service domain
        '.onrender.com',  # All Render subdomains
    ])
    
    # Railway fallback configuration (keep for potential return)
    RAILWAY_APP_HOSTNAME = os.getenv('RAILWAY_PUBLIC_DOMAIN')
    if RAILWAY_APP_HOSTNAME:
        ALLOWED_HOSTS.append(RAILWAY_APP_HOSTNAME)
    
    # Railway domains as fallback
    ALLOWED_HOSTS.extend(['.railway.app', '.up.railway.app'])

# Remove duplicates and None values
ALLOWED_HOSTS = list(set(filter(None, ALLOWED_HOSTS)))

if not ALLOWED_HOSTS and not DEBUG:
    # Fallback if no hosts are configured for production to prevent Django from refusing all connections
    print("WARNING: ALLOWED_HOSTS is empty in a non-DEBUG environment. This is insecure. Add your service's domain.")
    # ALLOWED_HOSTS = ['*'] # Highly insecure, for temporary debugging only if absolutely stuck



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'debug_toolbar',

    # Local apps
    # Add your project apps here, e.g.:
    # 'users',
    # 'finance',
    # 'budgeting',
    # 'expenses',
    'core',
]

# AUTH_USER_MODEL = 'core.User'

AUTHENTICATION_BACKENDS = [
    #'core.authentication.EmailOrPhoneNumberBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# CORS - Updated for Render with Railway fallback
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Local frontend
    "https://frontend-r2az.onrender.com",  # Old Render frontend (keep for safety or remove)
    "https://budget-pro-static-site.onrender.com",  # <--- ADD THIS NEW URL
    "https://auth-service-cdln.onrender.com",
    os.getenv('FRONTEND_URL'),
    os.getenv('AUTH_SERVICE_URL'),
]

# Added Railway URLs as fallback
railway_frontend = os.getenv('RAILWAY_FRONTEND_URL')
if railway_frontend:
    CORS_ALLOWED_ORIGINS.append(railway_frontend)

# Filter out None values
CORS_ALLOWED_ORIGINS = [origin for origin in CORS_ALLOWED_ORIGINS if origin]


# Settings for when THIS BMS service calls OTHER services
BMS_AUTH_KEY_FOR_DTS = os.getenv('API_KEY_FOR_BMS_TO_CALL_DTS') # Key BMS uses
DTS_STATUS_UPDATE_URL = os.getenv('DTS_STATUS_UPDATE_ENDPOINT_URL') # Target URL

# Keys expected from client services calling THIS (BMS) service

DTS_CLIENT_API_KEY_EXPECTED = os.getenv('DTS_CLIENT_API_KEY')
TTS_CLIENT_API_KEY_EXPECTED = os.getenv('TTS_CLIENT_API_KEY')
HDS_CLIENT_API_KEY_EXPECTED = os.getenv('HDS_CLIENT_API_KEY')
AMS_CLIENT_API_KEY_EXPECTED = os.getenv('AMS_CLIENT_API_KEY')

SERVICE_API_KEYS = {} # Maps the key value to the client service's name
if DTS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[DTS_CLIENT_API_KEY_EXPECTED] = "DTS"
if TTS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[TTS_CLIENT_API_KEY_EXPECTED] = "TTS"
    
# MODIFICATION START
if HDS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[HDS_CLIENT_API_KEY_EXPECTED] = "HDS"
if AMS_CLIENT_API_KEY_EXPECTED:
    SERVICE_API_KEYS[AMS_CLIENT_API_KEY_EXPECTED] = "AMS"
# MODIFICATION END

# Filter out None values if a key isn't set in .env
SERVICE_API_KEYS = {k: v for k, v in SERVICE_API_KEYS.items() if k}

CORS_ALLOW_ALL_ORIGINS = True  # For development - restrict in production
CORS_ALLOW_CREDENTIALS = True

# Email Configuration
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Debug toolbar settings
INTERNAL_IPS = [
    '127.0.0.1',
]

# JWT Settings

# JWT Signing Key - MUST match the centralized auth service's signing key
# This allows BMS to verify tokens issued by the centralized auth service
JWT_SIGNING_KEY = os.getenv('DJANGO_JWT_SIGNING_KEY', SECRET_KEY)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),  # Match auth service
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Match auth service
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'VERIFYING_KEY': None,
    'SIGNING_KEY': JWT_SIGNING_KEY,  # Use shared signing key
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Add for static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # For development
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [ 
        'core.authentication.JWTCookieAuthentication',  # Primary: JWT via cookies or Bearer header (centralized auth)
        'core.service_authentication.APIKeyAuthentication',  # For service-to-service API keys
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}

# Cache configuration for user data
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

ROOT_URLCONF = 'capstone.urls'


# DRF Spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "Budget Service API",
    "DESCRIPTION": "API for Budget Management",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],  # <-- Add this line
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_SECURITY_SCHEMES": {
        "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'defaultModelsExpandDepth': -1,  # Hide schemas section completely
    },
    'ENUM_NAME_OVERRIDES': {
       'Status0feEnum': 'BudgetProposalStatusEnum',
        'Status1a2Enum': 'ExpenseStatusEnum',
    },
    'TAGS': [  # Organize endpoints by category
        {'name': 'Authentication', 'description': 'User login/logout operations'},
    ],
    'APPEND_COMMON_PREFIX': False,
    'TAGS_SORTER': 'alpha',
    'OPERATION_SORTER': 'method',
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

# Allow SQLite for local development when no database config is provided
USE_SQLITE = os.getenv('USE_SQLITE', 'False').lower() == 'true'

if USE_SQLITE or (DEBUG and not DATABASE_URL and not os.getenv('DB_NAME')):
    # SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif DATABASE_URL:
    # Use Railway's DATABASE_URL (recommended)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Fallback to individual environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME') or os.getenv('PGDATABASE'),
            'USER': os.getenv('DB_USER') or os.getenv('PGUSER'),
            'PASSWORD': os.getenv('DB_PASSWORD') or os.getenv('PGPASSWORD'),
            'HOST': os.getenv('DB_HOST') or os.getenv('PGHOST', 'localhost'),
            'PORT': os.getenv('DB_PORT') or os.getenv('PGPORT', '5432'),
        }
    }


# Optional: Only needed if using Django's createsuperuser command
DJANGO_SUPERUSER_USERNAME = os.getenv('DJANGO_SUPERUSER_USERNAME')
DJANGO_SUPERUSER_EMAIL = os.getenv('DJANGO_SUPERUSER_EMAIL')
DJANGO_SUPERUSER_PASSWORD = os.getenv('DJANGO_SUPERUSER_PASSWORD')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'core.password_validators.CustomPasswordValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum 8 characters as per requirements
            'max_length': 64,  # Maximum 64 characters as per requirements
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {"NAME": "pwned_passwords_django.validators.PwnedPasswordsValidator",
     },  # Check against breached passwords

]

PASSWORD_HASHERS = [
    # 'core.hashers.CustomArgon2PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',      # Strongest
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',      # Default ; Fallback
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
