# Generated by Django 5.2.4 on 2025-10-21 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('failed_login_attempt', 'Failed Login Attempt'), ('password_reset', 'Password Reset'), ('login_success', 'Successful Login'), ('otp_generated', 'OTP Generated'), ('profile_updated', 'Profile Updated'), ('account_created', 'Account Created')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField(help_text='Plain text email body with placeholders like {user_name}, {timestamp}')),
                ('body_html', models.TextField(blank=True, help_text='HTML email body (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, help_text='User ID from auth service', null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data used for the notification')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'notification_type'], name='notificatio_user_id_46a8ea_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx'), models.Index(fields=['user_email'], name='notificatio_user_em_94b09a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, help_text='User ID from requesting service (optional)', null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('notification_type', models.CharField(max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed', 'created_at'], name='notificatio_process_c23b03_idx'), models.Index(fields=['user_id'], name='notificatio_user_id_a476a9_idx')],
            },
        ),
    ]
