# Generated by Django 5.2.3 on 2025-06-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_summary', models.TextField()),
                ('project_description', models.TextField()),
                ('performance_notes', models.TextField(blank=True)),
                ('department', models.IntegerField()),
                ('fiscal_year', models.IntegerField()),
                ('submitted_by_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('performance_start_date', models.DateField()),
                ('performance_end_date', models.DateField()),
                ('external_system_id', models.CharField(blank=True, max_length=100)),
                ('items', models.JSONField(default=list)),
            ],
        ),
    ]
