# Generated by Django 5.2.4 on 2025-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default='TK-000', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
