# Generated by Django 5.2.3 on 2025-06-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmscheckout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='ticket_id',
            field=models.CharField(default='TK-000', max_length=100),
        ),
    ]
