# Generated by Django 5.2.1 on 2025-06-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmscheckout', '0002_project_is_approved_project_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='external_system_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='items',
        ),
        migrations.RemoveField(
            model_name='project',
            name='performance_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='performance_notes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='performance_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_summary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='submitted_by_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
