# Generated by Django 5.2.4 on 2025-12-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_add_notification_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inappnotification",
            name="related_task_id",
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="related_task_item_id",
            field=models.CharField(
                blank=True,
                help_text="Related task item ID for navigation (links to user's specific assignment)",
                max_length=100,
                null=True,
            ),
        ),
    ]
