# Generated by Django 5.2.4 on 2025-11-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='roles',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='user_id',
        ),
        migrations.AddField(
            model_name='roles',
            name='system',
            field=models.CharField(default='tts', max_length=50),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RoleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='role.roles')),
            ],
            options={
                'ordering': ['role_id', 'user_id'],
                'unique_together': {('role_id', 'user_id')},
            },
        ),
    ]
