# Generated by Django 5.2 on 2026-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="URL to user's profile picture from central auth or uploaded to BMS", max_length=500, null=True),
        ),
    ]
