# Generated by Django 5.2 on 2025-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, help_text='ID of approving user from Auth Service', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_username',
            field=models.CharField(blank=True, help_text='Username of approving user', max_length=150, null=True),
        ),
    ]
