# Generated by Django 5.2 on 2025-06-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_approved_by_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='project',
            field=models.ForeignKey(help_text='The project this budget allocation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.project'),
        ),
    ]
