# Generated by Django 5.2 on 2025-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_budgetallocation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetproposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
    ]
