# Generated by Django 5.2 on 2025-10-29 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_budgetproposal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('algorithm_used', models.CharField(choices=[('LINEAR_PROJECTION', 'Linear Projection')], default='LINEAR_PROJECTION', max_length=50)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.fiscalyear')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastDataPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('month_name', models.CharField(max_length=10)),
                ('forecasted_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='core.forecast')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('forecast', 'month')},
            },
        ),
    ]
