# Generated by Django 5.2 on 2025-12-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_forecast_forecastdatapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='If True, this allocation requires Finance Manager approval before use.'),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='finance_manager_name',
            field=models.CharField(blank=True, help_text='Name of the finance operator who reviewed this proposal.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='signature',
            field=models.FileField(blank=True, help_text='Digital signature or attached approval document.', null=True, upload_to='budget_proposals/signatures/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_accomplished',
            field=models.BooleanField(default=False, help_text='True if the manual entry has been checked and verified by the Finance Manager.'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='classification',
            field=models.CharField(blank=True, choices=[('CAPEX', 'Capital Expenditure'), ('OPEX', 'Operational Expenditure'), ('MIXED', 'Mixed/Both')], help_text='Determines if this category is primarily CapEx, OpEx, or Mixed.', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expense_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.expense')),
            ],
        ),
    ]
