# Generated by Django 5.2 on 2025-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_budgetallocation_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
