# Generated by Django 5.2 on 2025-12-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_account_code_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetproposalitem',
            name='category',
            field=models.ForeignKey(help_text='The budget category this item belongs to (e.g., IT-HARDWARE).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.expensecategory'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department associated with this journal entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='expense_category',
            field=models.ForeignKey(blank=True, help_text='Specific budget category (e.g., Hardware, Travel) for this line item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expensecategory'),
        ),
    ]
