#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const chalk = require('chalk');

const CLI_DIR = __dirname;
const ENV_FILE = path.join(CLI_DIR, '.env');

/**
 * Find executable in PATH or common installation locations
 */
function findExecutable(name, commonPaths = []) {
  // Try common paths first
  for (const commonPath of commonPaths) {
    if (fs.existsSync(commonPath)) {
      return commonPath;
    }
  }

  // Try 'where' command (Windows)
  try {
    const result = execSync(`where ${name}`, { 
      encoding: 'utf8', 
      stdio: ['pipe', 'pipe', 'ignore'],
      shell: true
    });
    const foundPath = result.trim().split('\n')[0];
    if (foundPath && fs.existsSync(foundPath)) {
      return foundPath;
    }
  } catch (e) {
    // Not found via 'where', try 'which' (POSIX)
  }

  // Try 'which' command (POSIX/Git Bash)
  try {
    const result = execSync(`which ${name}`, { 
      encoding: 'utf8', 
      stdio: ['pipe', 'pipe', 'ignore'],
      shell: true
    });
    const foundPath = result.trim();
    if (foundPath && fs.existsSync(foundPath)) {
      return foundPath;
    }
  } catch (e) {
    // Not found
  }

  return null;
}

/**
 * Detect all available tools
 */
function detectTools() {
  const tools = {};

  console.log(chalk.cyan('\n🔍 Detecting environment...\n'));

  // Bash detection
  console.log('Looking for bash...');
  const bashPaths = [
    'C:\\Program Files\\Git\\bin\\bash.exe',
    'C:\\Program Files (x86)\\Git\\bin\\bash.exe',
  ];
  tools.bash = findExecutable('bash', bashPaths);
  if (tools.bash) {
    console.log(chalk.green(`  ✓ Found bash at: ${tools.bash}`));
  } else {
    console.log(chalk.yellow(`  ⚠ Bash not found`));
  }

  // Python detection
  console.log('Looking for python...');
  tools.python = findExecutable('python', []);
  if (tools.python) {
    console.log(chalk.green(`  ✓ Found python at: ${tools.python}`));
  } else {
    console.log(chalk.yellow(`  ⚠ Python not found`));
  }

  // PM2 detection
  console.log('Looking for pm2...');
  tools.pm2 = findExecutable('pm2', []);
  if (tools.pm2) {
    console.log(chalk.green(`  ✓ Found pm2 at: ${tools.pm2}`));
  } else {
    console.log(chalk.yellow(`  ⚠ PM2 not found`));
  }

  // PowerShell detection
  console.log('Looking for powershell...');
  tools.powershell = findExecutable('powershell', []);
  if (tools.powershell) {
    console.log(chalk.green(`  ✓ Found powershell at: ${tools.powershell}`));
  } else {
    console.log(chalk.yellow(`  ⚠ PowerShell not found`));
  }

  return tools;
}

/**
 * Generate .env file content
 */
function generateEnvContent(tools) {
  let content = `# CLI Configuration - Auto-generated by setup-env.js
# Generated at: ${new Date().toISOString()}
# Override these commands if your setup is non-standard

`;

  if (tools.bash) {
    content += `# Bash command\nBASH_CMD=${tools.bash}\n\n`;
  } else {
    content += `# Bash command (not found, using default)\n# BASH_CMD=bash\n\n`;
  }

  if (tools.python) {
    content += `# Python command\nPYTHON_CMD=${tools.python}\n\n`;
  } else {
    content += `# Python command (not found, using default)\n# PYTHON_CMD=python\n\n`;
  }

  if (tools.pm2) {
    content += `# PM2 command\nPM2_CMD=${tools.pm2}\n\n`;
  } else {
    content += `# PM2 command (not found, using default)\n# PM2_CMD=pm2\n\n`;
  }

  if (tools.powershell) {
    content += `# PowerShell command\nPOWERSHELL_CMD=${tools.powershell}\n`;
  } else {
    content += `# PowerShell command (not found, using default)\n# POWERSHELL_CMD=powershell\n`;
  }

  return content;
}

/**
 * Write .env file
 */
function writeEnvFile(content) {
  try {
    fs.writeFileSync(ENV_FILE, content, 'utf8');
    console.log(chalk.green(`\n✓ .env file created/updated at: ${ENV_FILE}\n`));
    return true;
  } catch (err) {
    console.log(chalk.red(`\n✗ Failed to write .env file: ${err.message}\n`));
    return false;
  }
}

/**
 * Display current .env content
 */
function displayEnvFile() {
  if (fs.existsSync(ENV_FILE)) {
    console.log(chalk.cyan('Current .env content:\n'));
    const content = fs.readFileSync(ENV_FILE, 'utf8');
    console.log(chalk.gray(content));
  }
}

/**
 * Main execution
 */
async function main() {
  console.log(chalk.bold.cyan('\n╔════════════════════════════════════════════════════╗'));
  console.log(chalk.bold.cyan('║   Capstone CLI Environment Setup                   ║'));
  console.log(chalk.bold.cyan('╚════════════════════════════════════════════════════╝'));

  const tools = detectTools();
  const envContent = generateEnvContent(tools);
  
  if (writeEnvFile(envContent)) {
    displayEnvFile();
    console.log(chalk.green('✓ Environment setup complete!\n'));
    console.log(chalk.cyan('You can now run:'));
    console.log(chalk.gray('  .\\ Scripts\\scripts.cmd\n'));
  } else {
    process.exit(1);
  }
}

main().catch(err => {
  console.error(chalk.red(`Error: ${err.message}`));
  process.exit(1);
});
