"""
Django settings for notification_service project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment detection
DJANGO_ENV = config('DJANGO_ENV', default='development')
IS_PRODUCTION = DJANGO_ENV.lower() == 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'DJANGO_SECRET_KEY',
    default='django-insecure-16*1i1yo%z4_*-#82g=+c5*few2=q2#k&^z_)lo_r&tl2szy1k' if not IS_PRODUCTION else None
)
if IS_PRODUCTION and not config('DJANGO_SECRET_KEY', default=None):
    raise ValueError('DJANGO_SECRET_KEY must be set in production environment')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default='False' if IS_PRODUCTION else 'True', cast=lambda x: x.lower() in ('true', '1', 'yes'))

ALLOWED_HOSTS = config(
    'DJANGO_ALLOWED_HOSTS',
    default='*' if DEBUG else 'localhost,127.0.0.1',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'django_celery_results',  # Add Celery results backend
    'whitenoise',  # Add Whitenoise for static file serving
    'corsheaders',  # Enable CORS handling
    
    # Local apps
    'notifications',
    'emails',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add CorsMiddleware early
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add Whitenoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'notification_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'emails', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notification_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DJANGO_ENV.lower() == 'production':
    # Use PostgreSQL in production via DATABASE_URL or individual env vars
    if config('DATABASE_URL', default=''):
        DATABASES = {
            'default': dj_database_url.config(
                default=config('DATABASE_URL'),
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('POSTGRES_DB', default='notification_db'),
                'USER': config('POSTGRES_USER', default='postgres'),
                'PASSWORD': config('POSTGRES_PASSWORD', default=''),
                'HOST': config('PGHOST', default='localhost'),
                'PORT': config('PGPORT', default=5432),
            }
        }
else:
    # Use SQLite in development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Enable compression and caching with Whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'notifications.authentication.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Email Configuration
# SendGrid in production, console backend in development
DEFAULT_FROM_EMAIL = config('DJANGO_DEFAULT_FROM_EMAIL', default='noreply@ticketflow.com')
SUPPORT_EMAIL = config('DJANGO_SUPPORT_EMAIL', default='support@ticketflow.com')

# SendGrid Configuration (for production)
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
SENDGRID_FROM_EMAIL = config('SENDGRID_FROM_EMAIL', default=DEFAULT_FROM_EMAIL)
SENDGRID_FROM_NAME = config('SENDGRID_FROM_NAME', default='TicketFlow')
SENDGRID_ENABLED = config('SENDGRID_ENABLED', default='False', cast=lambda x: x.lower() in ('true', '1', 'yes'))

# Django Email Backend Configuration
# Uses console in development, SMTP/SendGrid in production
EMAIL_BACKEND = config('DJANGO_EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend' if not IS_PRODUCTION else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('DJANGO_EMAIL_HOST', default='smtp.sendgrid.net')
EMAIL_PORT = config('DJANGO_EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('DJANGO_EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('DJANGO_EMAIL_HOST_USER', default='apikey')
EMAIL_HOST_PASSWORD = config('DJANGO_EMAIL_HOST_PASSWORD', default=SENDGRID_API_KEY)

# Notification Service Settings
NOTIFICATION_SERVICE_PORT = config('DJANGO_NOTIFICATION_SERVICE_PORT', default=8001, cast=int)
AUTH_SERVICE_URL = config('DJANGO_AUTH_SERVICE_URL', default='http://localhost:8000')

# Frontend links for ticket deep-links
TTS_FRONTEND_URL = config('TTS_FRONTEND_URL', default='http://localhost:1000')
TTS_TICKET_PATH_TEMPLATE = config('TTS_TICKET_PATH_TEMPLATE', default='/ticket/{id}')

# API Key Authentication for v2 endpoints
NOTIFICATION_API_KEYS = config(
    'DJANGO_NOTIFICATION_API_KEYS',
    default='demo-api-key-123,test-api-key-456',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# API Key for in-app notifications
API_KEY = config('DJANGO_API_KEY', default='in-app-notification-api-key-secure' if not IS_PRODUCTION else None)
if IS_PRODUCTION and not config('DJANGO_API_KEY', default=None):
    raise ValueError('DJANGO_API_KEY must be set in production environment')

# JWT Authentication settings
# Signing key for token verification - should match auth service
JWT_SIGNING_KEY = config(
    'DJANGO_JWT_SIGNING_KEY',
    default=SECRET_KEY  # Fallback to using Django's secret key if not explicitly provided
)

# Legacy: JWT_SHARED_SECRET_KEY kept for backward compatibility
JWT_SHARED_SECRET_KEY = JWT_SIGNING_KEY

# Celery Configuration
CELERY_BROKER_URL = config('DJANGO_CELERY_BROKER_URL', default='amqp://admin:admin@localhost:5672/')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Queues configuration for notification service
NOTIFICATION_QUEUE = config('DJANGO_NOTIFICATION_QUEUE', default='notification-queue')
INAPP_NOTIFICATION_QUEUE = config('DJANGO_INAPP_NOTIFICATION_QUEUE', default='inapp-notification-queue')
USER_SYNC_QUEUE = config('DJANGO_USER_SYNC_QUEUE', default='user-email-sync-queue')

CELERY_TASK_ROUTES = {
    # User email sync tasks (from auth service)
    'notifications.sync_user_email': {'queue': USER_SYNC_QUEUE},
    'notifications.bulk_sync_user_emails': {'queue': USER_SYNC_QUEUE},
    'notifications.delete_user_email_cache': {'queue': USER_SYNC_QUEUE},
    # In-app notification tasks
    'task.send_assignment_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    'notifications.create_inapp_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    'notifications.mark_notification_read': {'queue': INAPP_NOTIFICATION_QUEUE},
    'notifications.bulk_create_notifications': {'queue': INAPP_NOTIFICATION_QUEUE},
    # Task transfer notifications
    'notifications.send_task_transfer_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    # Task escalation notifications
    'notifications.send_escalation_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    # Task completion notifications
    'notifications.send_task_completed_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    # Workflow step change notifications
    'notifications.send_workflow_step_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    # SLA notifications
    'notifications.send_sla_warning_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    'notifications.send_sla_breach_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    # Ticket status notifications
    'notifications.send_ticket_status_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    # Comment notifications
    'notifications.send_comment_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    'notifications.send_mention_notification': {'queue': INAPP_NOTIFICATION_QUEUE},
    # Gmail API email tasks (sent from auth service)
    'notifications.send_email_via_gmail': {'queue': 'NOTIFICATION_TASKS'},
    'notifications.send_email_with_headers': {'queue': 'NOTIFICATION_TASKS'},
    'notifications.send_password_reset_email': {'queue': 'NOTIFICATION_TASKS'},
    'notifications.send_invitation_email': {'queue': 'NOTIFICATION_TASKS'},
    'notifications.send_otp_email': {'queue': 'NOTIFICATION_TASKS'},
    'notifications.send_system_addition_email': {'queue': 'NOTIFICATION_TASKS'},
}

# CORS configuration
# Always use environment variable if provided; defaults to localhost origins
CORS_ALLOWED_ORIGINS = config(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    default='http://localhost:1000,http://127.0.0.1:1000',
    cast=lambda v: [s.strip() for s in v.split(',')]
)
CORS_ALLOW_CREDENTIALS = config('DJANGO_CORS_ALLOW_CREDENTIALS', default='True', cast=lambda x: x.lower() in ('true', '1', 'yes'))
# Ensure common headers (Authorization, Content-Type, etc.) are allowed
CORS_ALLOW_HEADERS = list(default_headers)
