# Generated by Django 5.2.1 on 2025-06-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_ticket_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('source_service', models.CharField(db_index=True, default='ticket_service', max_length=50)),
                ('customer', models.JSONField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], db_index=True, default='Low', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], db_index=True, default='New', max_length=20, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('resolution_time', models.DurationField(blank=True, null=True)),
                ('time_closed', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_task_allocated', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['original_ticket_id'], name='tickets_tic_origina_c05aac_idx'), models.Index(fields=['source_service'], name='tickets_tic_source__f152b1_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'), models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'), models.Index(fields=['customer'], name='tickets_tic_custome_c43139_idx'), models.Index(fields=['department'], name='tickets_tic_departm_a49b1a_idx')],
            },
        ),
    ]
