# Generated by Django 5.2.1 on 2025-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_custome_c43139_idx',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='customer',
            new_name='employee',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['employee'], name='tickets_tic_employe_2c7711_idx'),
        ),
    ]
