# Generated by Django 5.2.4 on 2026-01-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleusers',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
