# Generated by Django 5.2.4 on 2025-11-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('design', models.JSONField(blank=True, default=dict, help_text='Store design coordinates {x, y} for frontend positioning')),
                ('is_initialized', models.BooleanField(default=False)),
                ('is_start', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.roles')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflows')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StepTransition',
            fields=[
                ('transition_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('design', models.JSONField(blank=True, default=dict, help_text='Store handles for frontend connections {source_handle, target_handle}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_step_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='step.steps')),
                ('to_step_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='step.steps')),
                ('workflow_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflows')),
            ],
        ),
    ]
