# Generated by Django 5.2.1 on 2025-06-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
