# Generated by Django 5.2.1 on 2025-06-23 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_steps_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='step_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
