# Generated by Django 5.2.1 on 2025-06-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_steps_step_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
