# Generated by Django 5.2.1 on 2025-06-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_steps_name'),
        ('workflow', '0004_remove_workflows_unique_main_sub_per_workflow_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steps',
            unique_together={('workflow_id', 'name')},
        ),
    ]
