# Generated by Django 5.2.4 on 2025-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_steps_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptransition',
            name='design',
            field=models.JSONField(blank=True, default=dict, help_text='Store handles for frontend connections {source_handle, target_handle}'),
        ),
    ]
