# Generated by Django 5.2.1 on 2025-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0005_alter_steps_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steps',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='steps',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
