# Generated by Django 5.2.4 on 2025-11-09 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='step.steps'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
