# Generated by Django 5.2.4 on 2025-11-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='transferred_by',
            field=models.IntegerField(blank=True, help_text='User ID of the admin who transferred this task', null=True),
        ),
    ]
