# Generated by Django 5.2.4 on 2025-11-09 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_current_step_task_status_task_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the task', max_length=36),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.JSONField(blank=True, default=list, help_text='Array of assigned users with format: [{userID, username, email, status, assigned_on, role}, ...]'),
        ),
    ]
