# Generated by Django 5.2.4 on 2025-11-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskitem_transferred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='origin',
            field=models.CharField(choices=[('System', 'System'), ('Transferred', 'Transferred'), ('Escalation', 'Escalation')], default='System', help_text='Origin of this assignment: System (auto-assigned), Transferred (admin transfer), or Escalation', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('reassigned', 'Reassigned'), ('escalated', 'Escalated'), ('breached', 'Breached')], default='new', help_text="Status of this user's assignment", max_length=50),
        ),
    ]
