# Generated by Django 5.2.4 on 2025-11-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_roundrobin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoundRobin',
        ),
    ]
