# Generated by Django 5.2.4 on 2025-12-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_taskitem_options_remove_taskitem_acted_on_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitemhistory',
            name='status_updated_on',
        ),
    ]
