# Generated by Django 5.2.1 on 2025-12-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('task', '0006_remove_taskitemhistory_status_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ticket_owner',
            field=models.ForeignKey(blank=True, help_text='Ticket Coordinator assigned as owner via round-robin rotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to='role.roleusers'),
        ),
    ]
