# Generated by Django 5.2.4 on 2025-11-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_taskitem_acted_on_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes provided during action transition'),
        ),
    ]
