# Generated by Django 5.2.1 on 2025-12-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_add_ticket_owner_to_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedNotification',
            fields=[
                ('failed_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='User ID to notify')),
                ('task_id', models.CharField(help_text='Task ID', max_length=50)),
                ('task_title', models.CharField(help_text='Task title/subject', max_length=255)),
                ('role_name', models.CharField(help_text='Role name', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Retry'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('success', 'Success')], default='pending', help_text='Current status of this notification', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details from failed attempt')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification first failed')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Last retry attempt', null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, help_text='When notification finally succeeded', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='task_failed_status_16a923_idx'), models.Index(fields=['user_id', 'task_id'], name='task_failed_user_id_b3eba9_idx')],
            },
        ),
    ]
