# Generated by Django 5.2.4 on 2025-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_taskitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Full name of the assigned user', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes provided during action transition'),
        ),
    ]
