# Generated by Django 5.2.4 on 2026-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_created_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
