# Generated by Django 5.2.4 on 2026-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ticketcomment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_auto_response',
            field=models.BooleanField(default=False),
        ),
    ]
