# Generated by Django 5.2.4 on 2026-01-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ticketcomment_is_auto_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_owner_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Ticket Coordinator user ID from auth service who owns this ticket', null=True),
        ),
    ]
