# Generated by Django 5.2.4 on 2026-01-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ticket_ticket_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(db_index=True, help_text='External employee ID from auth service')),
                ('notification_type', models.CharField(choices=[('ticket_submitted', 'Ticket Submitted'), ('ticket_approved', 'Ticket Approved'), ('ticket_rejected', 'Ticket Rejected'), ('ticket_in_progress', 'Ticket In Progress'), ('ticket_on_hold', 'Ticket On Hold'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_withdrawn', 'Ticket Withdrawn'), ('new_reply', 'New Reply'), ('owner_reply', 'Owner Reply')], default='ticket_submitted', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link_type', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_notifications', to='core.ticket')),
            ],
            options={
                'verbose_name': 'Employee Notification',
                'verbose_name_plural': 'Employee Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_id', 'is_read'], name='core_employ_employe_b7bbd8_idx'), models.Index(fields=['employee_id', '-created_at'], name='core_employ_employe_76c4db_idx')],
            },
        ),
    ]
