# Generated by Django 5.2.4 on 2026-01-11 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_employee_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
