# Generated by Django 5.2.4 on 2026-01-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_ticket_assigned_to_ticket_current_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for the article'),
        ),
    ]
