# Generated by Django 5.2.4 on 2026-01-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_knowledgearticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
