# Generated by Django 5.2.4 on 2026-01-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_ticket_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset_id',
            field=models.CharField(blank=True, help_text='AMS Asset ID (e.g., AST-20260110-00001-3451)', max_length=50, null=True),
        ),
    ]
