# Generated by Django 5.2.4 on 2026-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_asset_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticleversion',
            name='category_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knowledgearticleversion',
            name='description_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgearticleversion',
            name='subject_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgearticleversion',
            name='tags_snapshot',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='knowledgearticleversion',
            name='visibility_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
