# Generated by Django 5.2.4 on 2025-11-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('step', '0001_initial'),
        ('tickets', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the task', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('target_resolution', models.DateTimeField(blank=True, help_text='Target date and time for task resolution', null=True)),
                ('resolution_time', models.DateTimeField(blank=True, help_text='Actual date and time when the task was resolved', null=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='step.steps')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.workflowticket')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflows')),
                ('workflow_version', models.ForeignKey(blank=True, help_text='The specific version of the workflow used for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflow.workflowversion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('task_item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('acted', 'Acted'), ('escalated', 'Escalated'), ('transferred', 'Transferred')], default='assigned', help_text="Status of this user's assignment", max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes provided during action transition')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('status_updated_on', models.DateTimeField(blank=True, null=True)),
                ('target_resolution', models.DateTimeField(blank=True, help_text='Target date and time for task resolution', null=True)),
                ('resolution_time', models.DateTimeField(blank=True, help_text='Actual date and time when the task was resolved', null=True)),
                ('acted_on', models.DateTimeField(blank=True, null=True)),
                ('acted_on_step', models.ForeignKey(blank=True, help_text='The step where the user acted on this task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='step.steps')),
                ('role_user', models.ForeignKey(help_text='Link to RoleUsers for user and role info', on_delete=django.db.models.deletion.CASCADE, to='role.roleusers')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('transferred_to', models.ForeignKey(blank=True, help_text='User this task was transferred to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_task_items', to='role.roleusers')),
            ],
            options={
                'ordering': ['assigned_on'],
                'unique_together': {('task', 'role_user')},
            },
        ),
    ]
