# Generated by Django 5.2.4 on 2025-11-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskitem',
            unique_together=set(),
        ),
    ]
