# Generated by Django 5.2.4 on 2025-11-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
        ('task', '0004_taskitem_origin_alter_taskitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'ordering': ['task']},
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='acted_on_step',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='status_updated_on',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='assigned_on_step',
            field=models.ForeignKey(blank=True, help_text='The step where this task item was assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='step.steps'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True, help_text='When this assignment was created'),
        ),
        migrations.CreateModel(
            name='TaskItemHistory',
            fields=[
                ('task_item_history_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('resolved', 'Resolved'), ('reassigned', 'Reassigned'), ('escalated', 'Escalated'), ('breached', 'Breached')], help_text='Status at this point in history', max_length=50)),
                ('status_updated_on', models.DateTimeField(blank=True, help_text='When this status was updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this history record was created')),
                ('task_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskitemhistory_set', to='task.taskitem')),
            ],
            options={
                'verbose_name_plural': 'Task Item History',
                'ordering': ['task_item', 'created_at'],
            },
        ),
    ]
