# Generated by Django 5.2.4 on 2025-12-20 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_failednotification"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="failednotification",
            name="task_failed_user_id_b3eba9_idx",
        ),
        migrations.RemoveField(
            model_name="failednotification",
            name="task_id",
        ),
        migrations.AddField(
            model_name="failednotification",
            name="task_item_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Task Item ID",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="failednotification",
            index=models.Index(
                fields=["user_id", "task_item_id"],
                name="task_failed_user_id_386529_idx",
            ),
        ),
    ]
