# Generated by Django 5.2.4 on 2025-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='user_id',
            field=models.CharField(blank=True, help_text='User ID from auth service (can be UUID or integer)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='user_id',
            field=models.CharField(blank=True, help_text='User ID from requesting service (can be UUID or integer)', max_length=255, null=True),
        ),
    ]
