# Generated by Django 5.2.4 on 2025-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_email', models.EmailField(help_text='Email address of the Gmail account', max_length=254, unique=True)),
                ('token_data', models.TextField(help_text='Encrypted OAuth token data')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gmail_tokens',
                'ordering': ['-updated_at'],
            },
        ),
    ]
