# Generated by Django 5.2.4 on 2025-11-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.CharField(blank=True, help_text='Parent comment_id for replies', max_length=20, null=True),
        ),
    ]
