# Generated by Django 5.2.4 on 2025-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.CharField(blank=True, help_text='Parent comment_id for replies', max_length=50, null=True),
        ),
    ]
