from django.core.management.base import BaseCommand
from django.utils import timezone
from assets_ms.models import Component
from decimal import Decimal
from datetime import timedelta


class Command(BaseCommand):
    help = 'Seed the database with 100 component records'

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Clear existing components before seeding')

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write(self.style.WARNING('Clearing existing components...'))
            Component.objects.all().delete()
            self.stdout.write(self.style.SUCCESS('Existing components cleared.'))

        self.stdout.write(self.style.MIGRATE_HEADING('Creating 100 component records...'))
        components_data = self.get_components_data()
        created_count = 0
        skipped_count = 0

        for component_data in components_data:
            component, created = Component.objects.get_or_create(
                name=component_data['name'], model_number=component_data['model_number'], defaults=component_data
            )
            if created:
                created_count += 1
                if created_count % 10 == 0:
                    self.stdout.write(self.style.SUCCESS(f'✓ Created {created_count} components...'))
            else:
                skipped_count += 1

        self.stdout.write(self.style.SUCCESS(f'\n{"="*60}'))
        self.stdout.write(self.style.SUCCESS(f'Seeding Complete! Created: {created_count} | Skipped: {skipped_count}'))
        self.stdout.write(self.style.SUCCESS(f'{"="*60}\n'))

    def get_components_data(self):
        """Returns list of 100 component records

        Note: Categories, manufacturers, suppliers, and locations use IDs 1-10
        to match the context seeders (10 records each).

        Component Categories (from contexts):
        - Category 6: Hard Drives
        - Category 7: Memory (RAM)
        - Category 8: Processors (CPU)
        - Category 9: Graphics Cards
        - Category 10: Power Supplies
        """
        base_date = timezone.now().date()
        import random

        # Helper function to get random IDs 1-10
        def rand_id():
            return random.randint(1, 10)

        return [
            # RAM Components (15 items) - Using component category IDs
            {'name': 'Kingston 4GB DDR4 2666MHz', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'KVR26N19S6/4', 'order_number': 'ORD-2024-001', 'purchase_date': base_date - timedelta(days=30), 'purchase_cost': Decimal('25.99'), 'quantity': 80, 'minimum_quantity': 15, 'notes': 'DDR4 RAM 4GB modules'},
            {'name': 'Kingston 8GB DDR4 2666MHz', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'KVR26N19S8/8', 'order_number': 'ORD-2024-002', 'purchase_date': base_date - timedelta(days=25), 'purchase_cost': Decimal('45.99'), 'quantity': 120, 'minimum_quantity': 20, 'notes': 'DDR4 RAM 8GB modules'},
            {'name': 'Kingston 16GB DDR4 3200MHz', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'KVR32N22S8/16', 'order_number': 'ORD-2024-003', 'purchase_date': base_date - timedelta(days=20), 'purchase_cost': Decimal('75.99'), 'quantity': 60, 'minimum_quantity': 10, 'notes': 'DDR4 RAM 16GB high-speed'},
            {'name': 'Corsair Vengeance 8GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CMK8GX4M1A2666C16', 'order_number': 'ORD-2024-004', 'purchase_date': base_date - timedelta(days=45), 'purchase_cost': Decimal('49.99'), 'quantity': 50, 'minimum_quantity': 10, 'notes': 'Corsair Vengeance DDR4 8GB'},
            {'name': 'Corsair Vengeance 16GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CMK16GX4M1A2666C16', 'order_number': 'ORD-2024-005', 'purchase_date': base_date - timedelta(days=40), 'purchase_cost': Decimal('79.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': 'Corsair Vengeance DDR4 16GB'},
            {'name': 'Crucial 8GB DDR4 2400MHz', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CT8G4DFS824A', 'order_number': 'ORD-2024-006', 'purchase_date': base_date - timedelta(days=35), 'purchase_cost': Decimal('42.99'), 'quantity': 70, 'minimum_quantity': 12, 'notes': 'Crucial DDR4 8GB standard'},
            {'name': 'Crucial 16GB DDR4 2400MHz', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CT16G4DFD824A', 'order_number': 'ORD-2024-007', 'purchase_date': base_date - timedelta(days=30), 'purchase_cost': Decimal('72.99'), 'quantity': 45, 'minimum_quantity': 8, 'notes': 'Crucial DDR4 16GB standard'},
            {'name': 'G.Skill Ripjaws 8GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'F4-3200C16S-8GVK', 'order_number': 'ORD-2024-008', 'purchase_date': base_date - timedelta(days=50), 'purchase_cost': Decimal('47.99'), 'quantity': 35, 'minimum_quantity': 7, 'notes': 'G.Skill Ripjaws DDR4 8GB'},
            {'name': 'G.Skill Ripjaws 16GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'F4-3200C16S-16GVK', 'order_number': 'ORD-2024-009', 'purchase_date': base_date - timedelta(days=45), 'purchase_cost': Decimal('77.99'), 'quantity': 30, 'minimum_quantity': 6, 'notes': 'G.Skill Ripjaws DDR4 16GB'},
            {'name': 'Samsung 8GB DDR4 2666MHz', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'M378A1K43CB2-CTD', 'order_number': 'ORD-2024-010', 'purchase_date': base_date - timedelta(days=60), 'purchase_cost': Decimal('44.99'), 'quantity': 55, 'minimum_quantity': 10, 'notes': 'Samsung DDR4 8GB OEM'},
            {'name': 'Samsung 16GB DDR4 2666MHz', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'M378A2K43CB1-CTD', 'order_number': 'ORD-2024-011', 'purchase_date': base_date - timedelta(days=55), 'purchase_cost': Decimal('74.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': 'Samsung DDR4 16GB OEM'},
            {'name': 'HyperX Fury 8GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HX426C16FB3/8', 'order_number': 'ORD-2024-012', 'purchase_date': base_date - timedelta(days=70), 'purchase_cost': Decimal('46.99'), 'quantity': 48, 'minimum_quantity': 9, 'notes': 'HyperX Fury DDR4 8GB'},
            {'name': 'HyperX Fury 16GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HX426C16FB3/16', 'order_number': 'ORD-2024-013', 'purchase_date': base_date - timedelta(days=65), 'purchase_cost': Decimal('76.99'), 'quantity': 38, 'minimum_quantity': 7, 'notes': 'HyperX Fury DDR4 16GB'},
            {'name': 'Patriot Viper 8GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'PV48G320C6K', 'order_number': 'ORD-2024-014', 'purchase_date': base_date - timedelta(days=80), 'purchase_cost': Decimal('43.99'), 'quantity': 42, 'minimum_quantity': 8, 'notes': 'Patriot Viper DDR4 8GB'},
            {'name': 'Patriot Viper 16GB DDR4', 'category': 7, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'PV416G320C6K', 'order_number': 'ORD-2024-015', 'purchase_date': base_date - timedelta(days=75), 'purchase_cost': Decimal('73.99'), 'quantity': 32, 'minimum_quantity': 6, 'notes': 'Patriot Viper DDR4 16GB'},

            # Storage Components (20 items) - Hard Drives category
            {'name': 'Samsung 250GB SSD 870 EVO', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'MZ-77E250B', 'order_number': 'ORD-2024-016', 'purchase_date': base_date - timedelta(days=20), 'purchase_cost': Decimal('39.99'), 'quantity': 50, 'minimum_quantity': 10, 'notes': 'SATA III 2.5" SSD 250GB'},
            {'name': 'Samsung 500GB SSD 870 EVO', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'MZ-77E500B', 'order_number': 'ORD-2024-017', 'purchase_date': base_date - timedelta(days=18), 'purchase_cost': Decimal('59.99'), 'quantity': 60, 'minimum_quantity': 12, 'notes': 'SATA III 2.5" SSD 500GB'},
            {'name': 'Samsung 1TB SSD 870 EVO', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'MZ-77E1T0B', 'order_number': 'ORD-2024-018', 'purchase_date': base_date - timedelta(days=15), 'purchase_cost': Decimal('99.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': 'SATA III 2.5" SSD 1TB'},
            {'name': 'Crucial MX500 250GB SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CT250MX500SSD1', 'order_number': 'ORD-2024-019', 'purchase_date': base_date - timedelta(days=25), 'purchase_cost': Decimal('37.99'), 'quantity': 45, 'minimum_quantity': 9, 'notes': 'SATA III 2.5" SSD 250GB'},
            {'name': 'Crucial MX500 500GB SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CT500MX500SSD1', 'order_number': 'ORD-2024-020', 'purchase_date': base_date - timedelta(days=22), 'purchase_cost': Decimal('57.99'), 'quantity': 55, 'minimum_quantity': 11, 'notes': 'SATA III 2.5" SSD 500GB'},
            {'name': 'Crucial MX500 1TB SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CT1000MX500SSD1', 'order_number': 'ORD-2024-021', 'purchase_date': base_date - timedelta(days=19), 'purchase_cost': Decimal('94.99'), 'quantity': 35, 'minimum_quantity': 7, 'notes': 'SATA III 2.5" SSD 1TB'},
            {'name': 'WD Blue 500GB HDD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'WD5000AZLX', 'order_number': 'ORD-2024-022', 'purchase_date': base_date - timedelta(days=40), 'purchase_cost': Decimal('29.99'), 'quantity': 30, 'minimum_quantity': 6, 'notes': '3.5" SATA HDD 500GB 7200RPM'},
            {'name': 'WD Blue 1TB HDD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'WD10EZEX', 'order_number': 'ORD-2024-023', 'purchase_date': base_date - timedelta(days=38), 'purchase_cost': Decimal('44.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': '3.5" SATA HDD 1TB 7200RPM'},
            {'name': 'WD Blue 2TB HDD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'WD20EZAZ', 'order_number': 'ORD-2024-024', 'purchase_date': base_date - timedelta(days=35), 'purchase_cost': Decimal('54.99'), 'quantity': 35, 'minimum_quantity': 7, 'notes': '3.5" SATA HDD 2TB 5400RPM'},
            {'name': 'Seagate Barracuda 1TB HDD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'ST1000DM010', 'order_number': 'ORD-2024-025', 'purchase_date': base_date - timedelta(days=42), 'purchase_cost': Decimal('42.99'), 'quantity': 38, 'minimum_quantity': 7, 'notes': '3.5" SATA HDD 1TB 7200RPM'},
            {'name': 'Seagate Barracuda 2TB HDD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'ST2000DM008', 'order_number': 'ORD-2024-026', 'purchase_date': base_date - timedelta(days=39), 'purchase_cost': Decimal('52.99'), 'quantity': 32, 'minimum_quantity': 6, 'notes': '3.5" SATA HDD 2TB 7200RPM'},
            {'name': 'Kingston A400 240GB SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SA400S37/240G', 'order_number': 'ORD-2024-027', 'purchase_date': base_date - timedelta(days=28), 'purchase_cost': Decimal('34.99'), 'quantity': 48, 'minimum_quantity': 9, 'notes': 'SATA III 2.5" SSD 240GB'},
            {'name': 'Kingston A400 480GB SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SA400S37/480G', 'order_number': 'ORD-2024-028', 'purchase_date': base_date - timedelta(days=26), 'purchase_cost': Decimal('54.99'), 'quantity': 42, 'minimum_quantity': 8, 'notes': 'SATA III 2.5" SSD 480GB'},
            {'name': 'Kingston A400 960GB SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SA400S37/960G', 'order_number': 'ORD-2024-029', 'purchase_date': base_date - timedelta(days=24), 'purchase_cost': Decimal('89.99'), 'quantity': 28, 'minimum_quantity': 5, 'notes': 'SATA III 2.5" SSD 960GB'},
            {'name': 'SanDisk SSD Plus 240GB', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SDSSDA-240G', 'order_number': 'ORD-2024-030', 'purchase_date': base_date - timedelta(days=32), 'purchase_cost': Decimal('36.99'), 'quantity': 44, 'minimum_quantity': 8, 'notes': 'SATA III 2.5" SSD 240GB'},
            {'name': 'SanDisk SSD Plus 480GB', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SDSSDA-480G', 'order_number': 'ORD-2024-031', 'purchase_date': base_date - timedelta(days=29), 'purchase_cost': Decimal('56.99'), 'quantity': 38, 'minimum_quantity': 7, 'notes': 'SATA III 2.5" SSD 480GB'},
            {'name': 'Toshiba 1TB HDD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HDWD110', 'order_number': 'ORD-2024-032', 'purchase_date': base_date - timedelta(days=44), 'purchase_cost': Decimal('43.99'), 'quantity': 34, 'minimum_quantity': 6, 'notes': '3.5" SATA HDD 1TB 7200RPM'},
            {'name': 'Toshiba 2TB HDD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HDWD120', 'order_number': 'ORD-2024-033', 'purchase_date': base_date - timedelta(days=41), 'purchase_cost': Decimal('53.99'), 'quantity': 30, 'minimum_quantity': 6, 'notes': '3.5" SATA HDD 2TB 7200RPM'},
            {'name': 'Intel 660p 512GB NVMe SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SSDPEKNW512G8', 'order_number': 'ORD-2024-034', 'purchase_date': base_date - timedelta(days=16), 'purchase_cost': Decimal('64.99'), 'quantity': 36, 'minimum_quantity': 7, 'notes': 'M.2 NVMe SSD 512GB'},
            {'name': 'Intel 660p 1TB NVMe SSD', 'category': 6, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SSDPEKNW010T8', 'order_number': 'ORD-2024-035', 'purchase_date': base_date - timedelta(days=14), 'purchase_cost': Decimal('104.99'), 'quantity': 28, 'minimum_quantity': 5, 'notes': 'M.2 NVMe SSD 1TB'},

            # Peripherals (20 items) - Using generic category for peripherals
            {'name': 'Logitech M185 Wireless Mouse', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'M185-BLK', 'order_number': 'ORD-2024-036', 'purchase_date': base_date - timedelta(days=10), 'purchase_cost': Decimal('12.99'), 'quantity': 100, 'minimum_quantity': 20, 'notes': 'Wireless mouse with USB receiver'},
            {'name': 'Logitech M510 Wireless Mouse', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'M510-BLK', 'order_number': 'ORD-2024-037', 'purchase_date': base_date - timedelta(days=12), 'purchase_cost': Decimal('24.99'), 'quantity': 75, 'minimum_quantity': 15, 'notes': 'Wireless mouse ergonomic'},
            {'name': 'Logitech K120 Keyboard', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'K120-USB', 'order_number': 'ORD-2024-038', 'purchase_date': base_date - timedelta(days=15), 'purchase_cost': Decimal('14.99'), 'quantity': 90, 'minimum_quantity': 18, 'notes': 'USB wired keyboard'},
            {'name': 'Logitech MK270 Wireless Combo', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'MK270-COMBO', 'order_number': 'ORD-2024-039', 'purchase_date': base_date - timedelta(days=18), 'purchase_cost': Decimal('29.99'), 'quantity': 60, 'minimum_quantity': 12, 'notes': 'Wireless keyboard and mouse combo'},
            {'name': 'Microsoft Wired Mouse 600', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'MS-600', 'order_number': 'ORD-2024-040', 'purchase_date': base_date - timedelta(days=20), 'purchase_cost': Decimal('9.99'), 'quantity': 85, 'minimum_quantity': 17, 'notes': 'USB wired optical mouse'},
            {'name': 'Microsoft Wireless Mouse 900', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'MS-900', 'order_number': 'ORD-2024-041', 'purchase_date': base_date - timedelta(days=22), 'purchase_cost': Decimal('19.99'), 'quantity': 70, 'minimum_quantity': 14, 'notes': 'Wireless Bluetooth mouse'},
            {'name': 'Microsoft Wired Keyboard 600', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'KB-600', 'order_number': 'ORD-2024-042', 'purchase_date': base_date - timedelta(days=25), 'purchase_cost': Decimal('16.99'), 'quantity': 80, 'minimum_quantity': 16, 'notes': 'USB wired keyboard'},
            {'name': 'HP USB Optical Mouse', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HP-X500', 'order_number': 'ORD-2024-043', 'purchase_date': base_date - timedelta(days=28), 'purchase_cost': Decimal('8.99'), 'quantity': 95, 'minimum_quantity': 19, 'notes': 'USB wired optical mouse'},
            {'name': 'HP Wireless Mouse X3000', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HP-X3000', 'order_number': 'ORD-2024-044', 'purchase_date': base_date - timedelta(days=30), 'purchase_cost': Decimal('15.99'), 'quantity': 65, 'minimum_quantity': 13, 'notes': 'Wireless optical mouse'},
            {'name': 'Dell USB Optical Mouse', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'DELL-MS116', 'order_number': 'ORD-2024-045', 'purchase_date': base_date - timedelta(days=32), 'purchase_cost': Decimal('7.99'), 'quantity': 110, 'minimum_quantity': 22, 'notes': 'USB wired optical mouse'},
            {'name': 'Dell Wireless Mouse WM126', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'DELL-WM126', 'order_number': 'ORD-2024-046', 'purchase_date': base_date - timedelta(days=34), 'purchase_cost': Decimal('14.99'), 'quantity': 72, 'minimum_quantity': 14, 'notes': 'Wireless optical mouse'},
            {'name': 'Dell KB216 Wired Keyboard', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'DELL-KB216', 'order_number': 'ORD-2024-047', 'purchase_date': base_date - timedelta(days=36), 'purchase_cost': Decimal('13.99'), 'quantity': 88, 'minimum_quantity': 17, 'notes': 'USB wired keyboard'},
            {'name': 'Logitech C270 HD Webcam', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'C270-HD', 'order_number': 'ORD-2024-048', 'purchase_date': base_date - timedelta(days=38), 'purchase_cost': Decimal('29.99'), 'quantity': 45, 'minimum_quantity': 9, 'notes': 'HD 720p webcam with mic'},
            {'name': 'Logitech C920 HD Pro Webcam', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'C920-PRO', 'order_number': 'ORD-2024-049', 'purchase_date': base_date - timedelta(days=40), 'purchase_cost': Decimal('69.99'), 'quantity': 30, 'minimum_quantity': 6, 'notes': 'Full HD 1080p webcam'},
            {'name': 'USB 3.0 Hub 4-Port', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'USB3-HUB4', 'order_number': 'ORD-2024-050', 'purchase_date': base_date - timedelta(days=42), 'purchase_cost': Decimal('12.99'), 'quantity': 55, 'minimum_quantity': 11, 'notes': '4-port USB 3.0 hub'},
            {'name': 'USB 3.0 Hub 7-Port', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'USB3-HUB7', 'order_number': 'ORD-2024-051', 'purchase_date': base_date - timedelta(days=44), 'purchase_cost': Decimal('19.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': '7-port USB 3.0 hub powered'},
            {'name': 'Headset with Microphone', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'H390-USB', 'order_number': 'ORD-2024-052', 'purchase_date': base_date - timedelta(days=46), 'purchase_cost': Decimal('34.99'), 'quantity': 50, 'minimum_quantity': 10, 'notes': 'USB headset with noise cancelling'},
            {'name': 'Wireless Presenter Remote', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'R400-PRESENTER', 'order_number': 'ORD-2024-053', 'purchase_date': base_date - timedelta(days=48), 'purchase_cost': Decimal('24.99'), 'quantity': 25, 'minimum_quantity': 5, 'notes': 'Wireless presentation remote'},
            {'name': 'External DVD Writer', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'DVD-RW-EXT', 'order_number': 'ORD-2024-054', 'purchase_date': base_date - timedelta(days=50), 'purchase_cost': Decimal('29.99'), 'quantity': 20, 'minimum_quantity': 4, 'notes': 'USB external DVD writer'},
            {'name': 'Laptop Cooling Pad', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'COOL-PAD-15', 'order_number': 'ORD-2024-055', 'purchase_date': base_date - timedelta(days=52), 'purchase_cost': Decimal('19.99'), 'quantity': 35, 'minimum_quantity': 7, 'notes': 'Laptop cooling pad with fans'},

            # Power Supplies & Adapters (15 items) - Power Supplies category
            {'name': 'Dell 65W AC Adapter', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'LA65NS2-01', 'order_number': 'ORD-2024-056', 'purchase_date': base_date - timedelta(days=54), 'purchase_cost': Decimal('29.99'), 'quantity': 50, 'minimum_quantity': 10, 'notes': 'Compatible with Dell laptops'},
            {'name': 'Dell 90W AC Adapter', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'LA90PM111', 'order_number': 'ORD-2024-057', 'purchase_date': base_date - timedelta(days=56), 'purchase_cost': Decimal('39.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': 'Compatible with Dell laptops'},
            {'name': 'HP 45W AC Adapter', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HP-45W-USB-C', 'order_number': 'ORD-2024-058', 'purchase_date': base_date - timedelta(days=58), 'purchase_cost': Decimal('24.99'), 'quantity': 45, 'minimum_quantity': 9, 'notes': 'USB-C HP laptop charger'},
            {'name': 'HP 65W AC Adapter', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HP-65W-SMART', 'order_number': 'ORD-2024-059', 'purchase_date': base_date - timedelta(days=60), 'purchase_cost': Decimal('32.99'), 'quantity': 48, 'minimum_quantity': 9, 'notes': 'HP Smart AC adapter'},
            {'name': 'HP 90W AC Adapter', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HP-90W-SMART', 'order_number': 'ORD-2024-060', 'purchase_date': base_date - timedelta(days=62), 'purchase_cost': Decimal('42.99'), 'quantity': 35, 'minimum_quantity': 7, 'notes': 'HP Smart AC adapter 90W'},
            {'name': 'Lenovo 65W AC Adapter', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'LEN-65W-USBC', 'order_number': 'ORD-2024-061', 'purchase_date': base_date - timedelta(days=64), 'purchase_cost': Decimal('31.99'), 'quantity': 42, 'minimum_quantity': 8, 'notes': 'Lenovo USB-C 65W adapter'},
            {'name': 'Lenovo 90W AC Adapter', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'LEN-90W-RECT', 'order_number': 'ORD-2024-062', 'purchase_date': base_date - timedelta(days=66), 'purchase_cost': Decimal('38.99'), 'quantity': 38, 'minimum_quantity': 7, 'notes': 'Lenovo rectangular tip 90W'},
            {'name': 'Universal Laptop Charger 90W', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'UNI-90W-MULTI', 'order_number': 'ORD-2024-063', 'purchase_date': base_date - timedelta(days=68), 'purchase_cost': Decimal('34.99'), 'quantity': 30, 'minimum_quantity': 6, 'notes': 'Universal laptop charger with tips'},
            {'name': 'Power Strip 6-Outlet', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'PS-6OUT-SURGE', 'order_number': 'ORD-2024-064', 'purchase_date': base_date - timedelta(days=70), 'purchase_cost': Decimal('15.99'), 'quantity': 60, 'minimum_quantity': 12, 'notes': '6-outlet surge protector'},
            {'name': 'Power Strip 8-Outlet', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'PS-8OUT-SURGE', 'order_number': 'ORD-2024-065', 'purchase_date': base_date - timedelta(days=72), 'purchase_cost': Decimal('19.99'), 'quantity': 50, 'minimum_quantity': 10, 'notes': '8-outlet surge protector'},
            {'name': 'UPS 650VA Battery Backup', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'UPS-650VA', 'order_number': 'ORD-2024-066', 'purchase_date': base_date - timedelta(days=74), 'purchase_cost': Decimal('79.99'), 'quantity': 25, 'minimum_quantity': 5, 'notes': 'UPS battery backup 650VA'},
            {'name': 'UPS 1000VA Battery Backup', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'UPS-1000VA', 'order_number': 'ORD-2024-067', 'purchase_date': base_date - timedelta(days=76), 'purchase_cost': Decimal('129.99'), 'quantity': 20, 'minimum_quantity': 4, 'notes': 'UPS battery backup 1000VA'},
            {'name': 'USB-C Power Adapter 30W', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'USBC-30W-PD', 'order_number': 'ORD-2024-068', 'purchase_date': base_date - timedelta(days=78), 'purchase_cost': Decimal('22.99'), 'quantity': 55, 'minimum_quantity': 11, 'notes': 'USB-C Power Delivery 30W'},
            {'name': 'USB-C Power Adapter 65W', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'USBC-65W-PD', 'order_number': 'ORD-2024-069', 'purchase_date': base_date - timedelta(days=80), 'purchase_cost': Decimal('34.99'), 'quantity': 45, 'minimum_quantity': 9, 'notes': 'USB-C Power Delivery 65W'},
            {'name': 'Desktop PC Power Supply 500W', 'category': 10, 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'PSU-500W-80PLUS', 'order_number': 'ORD-2024-070', 'purchase_date': base_date - timedelta(days=82), 'purchase_cost': Decimal('49.99'), 'quantity': 22, 'minimum_quantity': 4, 'notes': '500W 80+ Bronze PSU'},

            # Network Equipment (15 items) - Using generic category
            {'name': 'TP-Link 5-Port Gigabit Switch', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'TL-SG105', 'order_number': 'ORD-2024-071', 'purchase_date': base_date - timedelta(days=84), 'purchase_cost': Decimal('19.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': '5-port unmanaged gigabit switch'},
            {'name': 'TP-Link 8-Port Gigabit Switch', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'TL-SG108', 'order_number': 'ORD-2024-072', 'purchase_date': base_date - timedelta(days=86), 'purchase_cost': Decimal('24.99'), 'quantity': 35, 'minimum_quantity': 7, 'notes': '8-port unmanaged gigabit switch'},
            {'name': 'TP-Link 16-Port Gigabit Switch', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'TL-SG116', 'order_number': 'ORD-2024-073', 'purchase_date': base_date - timedelta(days=88), 'purchase_cost': Decimal('49.99'), 'quantity': 20, 'minimum_quantity': 4, 'notes': '16-port unmanaged gigabit switch'},
            {'name': 'Netgear 8-Port Gigabit Switch', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'GS308-100', 'order_number': 'ORD-2024-074', 'purchase_date': base_date - timedelta(days=90), 'purchase_cost': Decimal('26.99'), 'quantity': 32, 'minimum_quantity': 6, 'notes': '8-port unmanaged gigabit switch'},
            {'name': 'Netgear 24-Port Gigabit Switch', 'category': rand_id(), 'manufacturer': rand_id(), 'location': rand_id(), 'supplier': rand_id(), 'model_number': 'GS324-100', 'order_number': 'ORD-2024-075', 'purchase_date': base_date - timedelta(days=92), 'purchase_cost': Decimal('99.99'), 'quantity': 15, 'minimum_quantity': 3, 'notes': '24-port unmanaged gigabit switch'},
            {'name': 'Cisco 24-Port Managed Switch', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SG250-26', 'order_number': 'ORD-2024-076', 'purchase_date': base_date - timedelta(days=94), 'purchase_cost': Decimal('299.99'), 'quantity': 10, 'minimum_quantity': 2, 'notes': '24-port managed gigabit switch'},
            {'name': 'WiFi Router AC1200', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'ARCHER-A6', 'order_number': 'ORD-2024-077', 'purchase_date': base_date - timedelta(days=96), 'purchase_cost': Decimal('49.99'), 'quantity': 25, 'minimum_quantity': 5, 'notes': 'Dual-band WiFi router AC1200'},
            {'name': 'WiFi Router AC1750', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'ARCHER-A7', 'order_number': 'ORD-2024-078', 'purchase_date': base_date - timedelta(days=98), 'purchase_cost': Decimal('69.99'), 'quantity': 20, 'minimum_quantity': 4, 'notes': 'Dual-band WiFi router AC1750'},
            {'name': 'WiFi Access Point AC1200', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'UAP-AC-LITE', 'order_number': 'ORD-2024-079', 'purchase_date': base_date - timedelta(days=100), 'purchase_cost': Decimal('89.99'), 'quantity': 18, 'minimum_quantity': 3, 'notes': 'UniFi AC Lite access point'},
            {'name': 'WiFi Access Point AC1750', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'UAP-AC-PRO', 'order_number': 'ORD-2024-080', 'purchase_date': base_date - timedelta(days=102), 'purchase_cost': Decimal('149.99'), 'quantity': 12, 'minimum_quantity': 2, 'notes': 'UniFi AC Pro access point'},
            {'name': 'Network Patch Panel 24-Port', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'PP-24-CAT6', 'order_number': 'ORD-2024-081', 'purchase_date': base_date - timedelta(days=104), 'purchase_cost': Decimal('39.99'), 'quantity': 15, 'minimum_quantity': 3, 'notes': '24-port CAT6 patch panel'},
            {'name': 'Network Patch Panel 48-Port', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'PP-48-CAT6', 'order_number': 'ORD-2024-082', 'purchase_date': base_date - timedelta(days=106), 'purchase_cost': Decimal('59.99'), 'quantity': 10, 'minimum_quantity': 2, 'notes': '48-port CAT6 patch panel'},
            {'name': 'PoE Injector Gigabit', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'POE-INJ-1G', 'order_number': 'ORD-2024-083', 'purchase_date': base_date - timedelta(days=108), 'purchase_cost': Decimal('14.99'), 'quantity': 30, 'minimum_quantity': 6, 'notes': 'Gigabit PoE injector 802.3af'},
            {'name': 'PoE Switch 8-Port', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'TL-SG1008P', 'order_number': 'ORD-2024-084', 'purchase_date': base_date - timedelta(days=110), 'purchase_cost': Decimal('59.99'), 'quantity': 18, 'minimum_quantity': 3, 'notes': '8-port gigabit PoE switch'},
            {'name': 'Fiber Optic Transceiver SFP', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'SFP-1G-SX', 'order_number': 'ORD-2024-085', 'purchase_date': base_date - timedelta(days=112), 'purchase_cost': Decimal('34.99'), 'quantity': 20, 'minimum_quantity': 4, 'notes': '1G SFP fiber transceiver'},

            # Cables & Accessories (15 items) - Using generic category
            {'name': 'CAT6 Ethernet Cable 3ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CAT6-3FT-BLU', 'order_number': 'ORD-2024-086', 'purchase_date': base_date - timedelta(days=5), 'purchase_cost': Decimal('4.99'), 'quantity': 150, 'minimum_quantity': 30, 'notes': 'CAT6 patch cable 3ft blue'},
            {'name': 'CAT6 Ethernet Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CAT6-6FT-BLU', 'order_number': 'ORD-2024-087', 'purchase_date': base_date - timedelta(days=6), 'purchase_cost': Decimal('6.99'), 'quantity': 140, 'minimum_quantity': 28, 'notes': 'CAT6 patch cable 6ft blue'},
            {'name': 'CAT6 Ethernet Cable 10ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CAT6-10FT-BLU', 'order_number': 'ORD-2024-088', 'purchase_date': base_date - timedelta(days=7), 'purchase_cost': Decimal('8.99'), 'quantity': 120, 'minimum_quantity': 24, 'notes': 'CAT6 patch cable 10ft blue'},
            {'name': 'CAT6 Ethernet Cable 25ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CAT6-25FT-BLU', 'order_number': 'ORD-2024-089', 'purchase_date': base_date - timedelta(days=8), 'purchase_cost': Decimal('12.99'), 'quantity': 80, 'minimum_quantity': 16, 'notes': 'CAT6 patch cable 25ft blue'},
            {'name': 'CAT6 Ethernet Cable 50ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CAT6-50FT-BLU', 'order_number': 'ORD-2024-090', 'purchase_date': base_date - timedelta(days=9), 'purchase_cost': Decimal('18.99'), 'quantity': 60, 'minimum_quantity': 12, 'notes': 'CAT6 patch cable 50ft blue'},
            {'name': 'HDMI Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HDMI-6FT-4K', 'order_number': 'ORD-2024-091', 'purchase_date': base_date - timedelta(days=10), 'purchase_cost': Decimal('7.99'), 'quantity': 100, 'minimum_quantity': 20, 'notes': 'HDMI 2.0 cable 6ft 4K'},
            {'name': 'HDMI Cable 10ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'HDMI-10FT-4K', 'order_number': 'ORD-2024-092', 'purchase_date': base_date - timedelta(days=11), 'purchase_cost': Decimal('9.99'), 'quantity': 85, 'minimum_quantity': 17, 'notes': 'HDMI 2.0 cable 10ft 4K'},
            {'name': 'DisplayPort Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'DP-6FT-4K', 'order_number': 'ORD-2024-093', 'purchase_date': base_date - timedelta(days=12), 'purchase_cost': Decimal('9.99'), 'quantity': 70, 'minimum_quantity': 14, 'notes': 'DisplayPort 1.4 cable 6ft'},
            {'name': 'USB-C to USB-A Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'USBC-A-6FT', 'order_number': 'ORD-2024-094', 'purchase_date': base_date - timedelta(days=13), 'purchase_cost': Decimal('8.99'), 'quantity': 90, 'minimum_quantity': 18, 'notes': 'USB-C to USB-A 3.0 cable'},
            {'name': 'USB-C to USB-C Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'USBC-C-6FT', 'order_number': 'ORD-2024-095', 'purchase_date': base_date - timedelta(days=14), 'purchase_cost': Decimal('10.99'), 'quantity': 75, 'minimum_quantity': 15, 'notes': 'USB-C to USB-C 3.1 cable'},
            {'name': 'VGA Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'VGA-6FT', 'order_number': 'ORD-2024-096', 'purchase_date': base_date - timedelta(days=15), 'purchase_cost': Decimal('5.99'), 'quantity': 50, 'minimum_quantity': 10, 'notes': 'VGA monitor cable 6ft'},
            {'name': 'DVI Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'DVI-D-6FT', 'order_number': 'ORD-2024-097', 'purchase_date': base_date - timedelta(days=16), 'purchase_cost': Decimal('7.99'), 'quantity': 45, 'minimum_quantity': 9, 'notes': 'DVI-D dual link cable 6ft'},
            {'name': 'Audio 3.5mm Cable 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'AUX-6FT', 'order_number': 'ORD-2024-098', 'purchase_date': base_date - timedelta(days=17), 'purchase_cost': Decimal('4.99'), 'quantity': 80, 'minimum_quantity': 16, 'notes': '3.5mm audio cable 6ft'},
            {'name': 'Cable Management Sleeve 6ft', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'CABLE-SLEEVE-6FT', 'order_number': 'ORD-2024-099', 'purchase_date': base_date - timedelta(days=18), 'purchase_cost': Decimal('9.99'), 'quantity': 40, 'minimum_quantity': 8, 'notes': 'Cable management sleeve 6ft'},
            {'name': 'Velcro Cable Ties 100-Pack', 'category': rand_id(), 'manufacturer': rand_id(), 'supplier': rand_id(), 'location': rand_id(), 'model_number': 'VELCRO-TIES-100', 'order_number': 'ORD-2024-100', 'purchase_date': base_date - timedelta(days=19), 'purchase_cost': Decimal('12.99'), 'quantity': 50, 'minimum_quantity': 10, 'notes': 'Reusable velcro cable ties'},
        ]
