# Generated by Django 5.2.4 on 2025-11-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('action_log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.actions')),
            ],
        ),
    ]
