# Generated by Django 5.2.1 on 2025-06-18 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('action_log', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task', to_field='task_id'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.actions', to_field='action_id'),
        ),
    ]
