# Generated by Django 5.2.4 on 2025-11-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action_log', '0001_initial'),
        ('step_instance', '0001_initial'),
        ('task', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='step_instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step_instance.stepinstance', to_field='step_instance_id'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
