# Generated by Django 5.2.1 on 2025-06-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_log', '0002_actionlog_task_id_alter_actionlog_action_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
