# Generated by Django 5.2.4 on 2025-11-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_log', '0002_initial'),
        ('step_instance', '0002_remove_stepinstance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='step_instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step_instance.stepinstance'),
        ),
    ]
