# Generated by Django 5.2.1 on 2025-06-22 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_log', '0003_actionlog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
