# Generated by Django 5.2.1 on 2025-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_log', '0004_actionlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
